### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by nalauder** [jrowberg/bglib#29]
Unable to find whether or not this is possible. Can i connect at least two modules simultaneously to the dingle?

Cheers

**Comment by jrowberg** [comment]
The Bluegiga stack for BLExxx devices supports simultaneous connections with up to 8 slaves at the same time. **This only applies to the device operating in master mode, i.e. the one initiating outgoing connection requests.** A single slave can accept an incoming connection from only a single master, and cannot simultaneously connect with any other device. These are Bluetooth 4.0 LE devices which implement a typical star network topology.

**Comment by nalauder** [comment]
Using the dongle, i am successfully able to connect to one module. So far i haven't been able to connect to a second module simultaneously. Is this possible with this library?

**Comment by jrowberg** [comment]
Continued in #30.
