### ISSUE TITLE
Missing attributes.txt file in firmware folders

### ISSUE THREAD

**Issue by tunjid** [jrowberg/bglib#36]
The last time I used this library about two years ago, the gatt.xml only had 2 gatt characteristics for the the data transceiver service, and the slave stub sketch reflects that. The gatt.xml has since been updated to have 4 gatt characteristics, but with no attributes.txt file, it's impossible to know what the gatt handles are for these characteristics without reflashing the firmware.

The commit that removed them has the hash: e0f1dbeb849faaacd768aae68b6b3fdd5a7378ab
The commit adding the new characteristics is: ea3e9188f7eb26256ce5cfb8a5cc848eaaf8a796

Do you happen to have the attributes.txt file handy? Thanks.

**Comment by jrowberg** [comment]
The firmware doesn't need to be reflashed, but simply recompiled. This will generate all of the bgbuild.exe output files. The output from that GATT structure is attached here.

[attributes.txt](https://github.com/jrowberg/bglib/files/834747/attributes.txt)
