### ISSUE TITLE
interpreting Bluegiga.BLE.Events.Connection.DisconnectedEventArgs.reason

### ISSUE THREAD

**Issue by fschwiet** [jrowberg/bglib#48]
Where can I look up the meaning of status codes for Bluegiga.BLE.Events.Connection.DisconnectedEventArgs.reason?  I was seeing 0x208 as the DisconnectedEventArgs.reason.   

I see 0x208 defined as connection timeout in https://www.silabs.com/documents/login/reference-manuals/Bluetooth_Smart_Software-BLE-1.6-API-RM.pdf in section 5.11.1 “BGAPI errors”, but I'm not sure the documentation applies to DisconnectedEventArgs.reason.

**Comment by mjbrown** [comment]
It is in the BGAPI main documentation near the bottom. Or there's a lookup table in Python here: https://github.com/mjbrown/bgapi/blob/master/bgapi/cmd_def.py

**Comment by fschwiet** [comment]
Great, thank you.
