### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by mash** [jrowberg/bglib#6]
I want to use your BGLib library in my opensource arduino related project.
Particularly BGLib.cpp, BGLib.h, BGLibConfig.h .
But haven't found any information related to licensing.

I expect it :) to be something like MIT License, but how do you think?

**Comment by ckuhn203** [comment]
Project is MIT licensed. 
https://github.com/jrowberg/bglib/blob/master/LICENSE.md

Could probably close this.
