### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by xloem** [jrowberg/bglib#61]
I ported bglib to a C++ class at https://github.com/xloem/bglibpp .

Is this something you'd be interested in adding to your repository for people to find?

**Comment by jrowberg** [comment]
Thanks for the heads-up on this project. I've added a link to your repository in the main README at the top level of my bglib repo. Well done!

**Comment by xloem** [comment]
Thanks!  I actually meant, I was wondering if you wanted to host the code alongside the other implementations, in your repository, but I suppose the readme link works fine.
